/**
 * Copies compiled ABIs into packages/shared/src/abi so the API, indexer and
 * frontend can import them without depending on hardhat artifacts at runtime.
 * Run automatically as part of `npm run compile`.
 */
import * as fs from 'fs';
import * as path from 'path';

const CONTRACTS = ['EnterpriseToken', 'AssetRegistry', 'PermissionedTransfer'];

const artifactsDir = path.resolve(__dirname, '..', 'artifacts', 'contracts');
const outDir = path.resolve(__dirname, '..', '..', 'packages', 'shared', 'src', 'abi');
fs.mkdirSync(outDir, { recursive: true });

for (const name of CONTRACTS) {
  const artifactPath = path.join(artifactsDir, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(artifactPath)) {
    throw new Error(`artifact not found: ${artifactPath} (run hardhat compile first)`);
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8')) as { abi: unknown[] };
  const target = path.join(outDir, `${name}.ts`);
  const body =
    `// AUTO-GENERATED by contracts/scripts/export-abi.ts — do not edit.\n` +
    `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  fs.writeFileSync(target, body);
  console.log(`exported ${name} ABI -> ${path.relative(process.cwd(), target)}`);
}

const index =
  `// AUTO-GENERATED by contracts/scripts/export-abi.ts — do not edit.\n` +
  CONTRACTS.map((n) => `export { ${n}Abi } from './${n}.js';`).join('\n') +
  '\n';
fs.writeFileSync(path.join(outDir, 'index.ts'), index);
